In [12]:
# Importação de Bibliotecas
import numpy as np

In [13]:
# Códigos da atividade passada (Matriz Inversa)
def retirar_linha_coluna(array, linha_remover, coluna_remover):
    nova_matriz = []

    for i, linha in enumerate(array):
        if i != linha_remover:
            nova_linha = []
            for j, elemento in enumerate(linha):
                if j != coluna_remover:
                    nova_linha.append(elemento)
            nova_matriz.append(nova_linha)
    return nova_matriz

def determinante(array):
    tamanho = len(array)
    if len(array) == 1:
        return array[0][0]
    if len(array) == 2:
        return array[0][0]*array[1][1] - array[0][1]*array[1][0]
    det = 0
    for coluna in range(tamanho):
        submatriz = retirar_linha_coluna(array, 0, coluna)
        cofator = ((-1) ** coluna) * array[0][coluna] * determinante(submatriz)
        det += cofator  
    return det

def cofator(array, i, j):
    submatriz = retirar_linha_coluna(array, i, j)
    cofator_val = ((-1) ** (i + j)) * determinante(submatriz)
    return cofator_val

def matriz_transposta(array):
    transposta = []
    num_linhas = len(array)
    num_colunas = len(array[0])

    for j in range(num_colunas):
        nova_linha = []
        for i in range(num_linhas):
            nova_linha.append(array[i][j])
        transposta.append(nova_linha)
    return transposta

def matriz_inversa(array):
    matriz = list(array)
    determinante_array = determinante(array)
    if determinante_array != 0:
        matriz_aji = []
        matriz_aji = []
        for i in range(len(array)):
            linha_aji = []
            for j in range(len(array[i])):
                item_cofator = cofator(array, i, j)
                linha_aji.append(item_cofator)
            matriz_aji.append(linha_aji)
        matriz_aji = np.array(matriz_aji)
        #print(matriz_aji)
        matriz_adj = matriz_transposta(matriz_aji)
        #print(matriz_adj)
        matriz_adj = np.array(matriz_adj)
        matriz_inversa = (1/determinante_array) * matriz_adj
    else:
        raise ValueError("Não é possível calcular a matriz inversa de matrizes com determinante igual a 0!")
    return matriz_inversa

In [14]:
matrizA = np.array([[2,1,1,0],[0,1,1,1],[0,0,2,2],[0,0,0,2]])
matrizx = np.array([["x"],["y"],["z"],["w"]])
matrizB = np.array([[2], [-1], [-4], [-2]])

def verificador_matriz_triangular_superior(matriz):
    """Essa função, teorciamente, é meio inútil, mas ainda funciona e é divertida"""
    contador = 0
    verificador_de_mts = 0
    tamanho_matriz = len(matriz)

    for i in range(tamanho_matriz):
        for j in range(tamanho_matriz):
            if j < i: 
                contador += 1 
                if matriz[i, j] == 0:
                    verificador_de_mts += 1
            

    if verificador_de_mts == contador:
        return True
    else:
        return False

def resolucao_sl_por_matriz_inversa(matrizA, matrizx, matrizB):
    """Sei que era para fazer apenas pelo método recursivo, mas já estava quase pronto, então só fiz"""
    if verificador_matriz_triangular_superior(matrizA):
        matrizA_inversa = matriz_inversa(matrizA)
        matrizx_resolvida = matrizA_inversa @ matrizB
        return matrizx_resolvida
    else:
        ValueError("Essa matriz não é triangular superior :(")
    
resolucao_sl_por_matriz_inversa(matrizA, matrizx, matrizB)

array([[ 1.],
       [ 1.],
       [-1.],
       [-1.]])

In [15]:
def decodificando_variáveis(matrizx, matrizx_resolvida):
    """Apenas uma brincadeira para ajudar na visualização da resolução do sistema linear"""
    
    for variavel,resultado in zip(matrizx, matrizx_resolvida):
        print(f"A variável {variavel} é igual a {resultado}")
matrizx_resolvida = resolucao_sl_por_matriz_inversa(matrizA, matrizx, matrizB)
decodificando_variáveis(matrizx, matrizx_resolvida)

A variável ['x'] é igual a [1.]
A variável ['y'] é igual a [1.]
A variável ['z'] é igual a [-1.]
A variável ['w'] é igual a [-1.]


In [16]:
def resolucao_matriz_triangular_superior(matrizA, matrizB):
    """Agora sim é o código certo."""
    tamanho = len(matrizA)
    solucao = np.zeros(tamanho)
    
    for linha in range(tamanho - 1, -1, -1):
        soma = 0
        for coluna in range(linha + 1, tamanho):
            soma += matrizA[linha][coluna] * solucao[coluna]
        
        solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha]
        
    return solucao


In [17]:
def eliminacao_gaussiana(MatrizA, MatrizB):
    """Função para resolver a Gaussiana. Por favor, ignore a parte sobre atualização"""
    tamanho = len(MatrizA)
    for i in range(tamanho):
        for j in range(i + 1, tamanho):
            mij = MatrizA[j][i] / MatrizA[i][i]
            MatrizB[j] = MatrizB[j] - mij * MatrizB[i]
            for k in range(i, tamanho):
                MatrizA[j][k] = MatrizA[j][k] - mij * MatrizA[i][k]
                
    resolucao = resolucao_matriz_triangular_superior(MatrizA, MatrizB)
    return resolucao

MatrizA = np.array([[2,1,1,0], [4,3,3,1], [8,7,9,5], [6,7,9,8]])
MatrizB= np.array([[2], [3], [1], [-4]])

eliminacao_gaussiana(MatrizA, MatrizB)


C:\Users\julia24002\AppData\Local\Temp\ipykernel_41692\3307349425.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha]


array([ 1.,  1., -1., -1.])

In [41]:
# Eliminação Gaussiana com pivoteamento
# Ajuda: Ana Luz

def linha_mais_valiosa(MatrizA, tamanho, j):
    maior_valor = float("-inf")
    indice_maior_valor = tamanho
    for i in range(tamanho):
        if abs(MatrizA[i][j])> maior_valor:
            indice_maior_valor = i
            maior_valor = abs(MatrizA[i][j])
            
    return indice_maior_valor

def trocar_linha(MatrizA, MatrizB, linha, coluna):
    tamanho = len(MatrizA)
        
    linha_maior_valor_DP = linha_mais_valiosa(MatrizA, tamanho, coluna)
    
    MatrizA[[linha, linha_maior_valor_DP]] = MatrizA[[linha_maior_valor_DP, linha]]
    
    MatrizB[[linha, linha_maior_valor_DP]] = MatrizB[[linha_maior_valor_DP, linha]]
        
    return MatrizA, MatrizB

def eliminacao_gaussiana_com_pivotiamento(MatrizA, MatrizB):
    """Função para resolver a Gaussiana com pivoteamento. Finalmente deu certo :)"""

    tamanho = len(MatrizA)
    
    MatrizA, MatrizB = trocar_linha(MatrizA, MatrizB, tamanho-1, tamanho-1)
    
    for i in range(tamanho):
        
        for j in range(i + 1, tamanho):
            mij = MatrizA[j][i] / MatrizA[i][i]
            MatrizB[j] = MatrizB[j] - mij * MatrizB[i]
            for k in range(i, tamanho):
                MatrizA[j][k] = MatrizA[j][k] - mij * MatrizA[i][k]
                
    resolucao = resolucao_matriz_triangular_superior(MatrizA, MatrizB)
    return resolucao

MatrizA1 = np.array([[2,1,1,0], [4,3,3,1], [8,7,9,5], [6,7,9,8]])
MatrizB1= np.array([[2], [3], [1], [-4]])

eliminacao_gaussiana_com_pivotiamento(MatrizA1, MatrizB1)

C:\Users\julia24002\AppData\Local\Temp\ipykernel_41692\3307349425.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha]


array([ 1.,  1., -1., -1.])

In [45]:
matrizv = np.array([[1,0.1,0.01, 0.001], [1,0.2, 0.04, 0.008], [1,0.3, 0.09, 0.027], [1, 0.4, 0.09, 0.027]])
matriza = np.array([[5], [13], [-4], [-8]])
a = list(eliminacao_gaussiana_com_pivotiamento(matrizv, matriza))
for i in a:
    print(round(i,2))

-0.27
-50.0
1472.73
-4454.55


C:\Users\julia24002\AppData\Local\Temp\ipykernel_41692\3307349425.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha]
