In [8]:
import numpy as np

In [9]:
A = [
    [3,2,4],
    [1,1,2],
    [4,3,2]
]
matrizA = np.array(A)
print(matrizA)
#print(list(matrizA.shape))

[[3 2 4]
 [1 1 2]
 [4 3 2]]


In [10]:
def retirar_linha_coluna(array, linha_remover, coluna_remover):
    nova_matriz = []

    for i, linha in enumerate(array):
        if i != linha_remover:
            nova_linha = []
            for j, elemento in enumerate(linha):
                if j != coluna_remover:
                    nova_linha.append(elemento)
            nova_matriz.append(nova_linha)
    return nova_matriz

def determinante(array):
    """ Tentativa de fazer um algoritmo recursivo para cálculo de determinante a partir do método de Laplace"""
    tamanho = len(array)
    if len(array) == 1:
        return array[0][0]
    if len(array) == 2:
        return array[0][0]*array[1][1] - array[0][1]*array[1][0]
    det = 0
    for coluna in range(tamanho):
        submatriz = retirar_linha_coluna(array, 0, coluna)
        cofator = ((-1) ** coluna) * array[0][coluna] * determinante(submatriz)
        det += cofator
        
    return det
len(matrizA)
determinante(matrizA)

-4

In [11]:
def cofator(array, i, j):
    submatriz = retirar_linha_coluna(array, i, j)
    cofator_val = ((-1) ** (i + j)) * determinante(submatriz)
    return cofator_val

def matriz_transposta(array):
    transposta = []
    num_linhas = len(array)
    num_colunas = len(array[0])

    for j in range(num_colunas):
        nova_linha = []
        for i in range(num_linhas):
            nova_linha.append(array[i][j])
        transposta.append(nova_linha)
    return transposta

def matriz_inversa(array):
    matriz = list(array)
    determinante_array = determinante(array)
    if determinante_array != 0:
        matriz_aji = []
        matriz_aji = []
        for i in range(len(array)):
            linha_aji = []
            for j in range(len(array[i])):
                item_cofator = cofator(array, i, j)
                linha_aji.append(item_cofator)
            matriz_aji.append(linha_aji)
        matriz_aji = np.array(matriz_aji)
        print(matriz_aji)
        matriz_adj = matriz_transposta(matriz_aji)
        print(matriz_adj)
        matriz_adj = np.array(matriz_adj)
        matriz_inversa = (1/determinante_array) * matriz_adj
    else:
        raise ValueError("Não é possível calcular a matriz inversa de matrizes com determinante igual a 0!")
    return "A matriz inversa é igual a", matriz_inversa

matriz_inversa(matrizA)

[[ -4   6  -1]
 [  8 -10  -1]
 [  0  -2   1]]
[[-4, 8, 0], [6, -10, -2], [-1, -1, 1]]


('A matriz inversa é igual a',
 array([[ 1.  , -2.  , -0.  ],
        [-1.5 ,  2.5 ,  0.5 ],
        [ 0.25,  0.25, -0.25]]))

In [13]:
matrizB = np.array([[2,1,1,0], [0,1,1,1], [0,0,2,2], [0,0,0,2]])
m = matriz_inversa(matrizB)
determinante(matrizB)

[[ 4  0  0  0]
 [-4  8  0  0]
 [ 0 -4  4  0]
 [ 2  0 -4  4]]
[[4, -4, 0, 2], [0, 8, -4, 0], [0, 0, 4, -4], [0, 0, 0, 4]]


8

In [15]:
def matriz_inversaa(matrizA):
    """Método mais fácil para resolver matriz inversa"""
    matrizA = np.array(matrizA)
    detA = determinante(matrizA)
    if detA != 0:
        print(f"O determinante da matriz A é igual a {detA}. Logo, é possível calcular a matriz B!")
        matrizB = np.linalg.inv(matrizA)
        print("A matriz inversa de A (matriz B) é")
        print(matrizB)
        # print(np.round(matrizA @ matrizB, 2)) #Esse resultado deverá ser igual a uma matriz identidade
    else:
        print(f"O determinante da matriz A é igual a 0. Logo, não é possível calcular a matriz B :(")
matriz_inversaa(A)

O determinante da matriz A é igual a -4. Logo, é possível calcular a matriz B!
A matriz inversa de A (matriz B) é
[[ 1.   -2.    0.  ]
 [-1.5   2.5   0.5 ]
 [ 0.25  0.25 -0.25]]


In [16]:
matrizA = np.array([[2,1,1,0],[0,1,1,0],[0,0,2,2],[0,0,0,2]])

matriz_inversaa(matrizA)

O determinante da matriz A é igual a 8. Logo, é possível calcular a matriz B!
A matriz inversa de A (matriz B) é
[[ 0.5 -0.5  0.   0. ]
 [ 0.   1.  -0.5  0.5]
 [ 0.   0.   0.5 -0.5]
 [ 0.   0.   0.   0.5]]


## Bibliografia!

[1] Cassar, Daniel Roberto. "Módulo Numpy". Acesso em 11 de agosto de 2024. (Apostila da disciplina de probabilidade e estatística)