#### 📚  **Importação de bibliotecas**

In [2]:
import numpy as np

#### 📁 **Códigos das atividades passadas**

In [3]:
# Matriz Inversa
def retirar_linha_coluna(array, linha_remover, coluna_remover):
    nova_matriz = []

    for i, linha in enumerate(array):
        if i != linha_remover:
            nova_linha = []
            for j, elemento in enumerate(linha):
                if j != coluna_remover:
                    nova_linha.append(elemento)
            nova_matriz.append(nova_linha)
    return nova_matriz

def determinante(array):
    tamanho = len(array)
    if len(array) == 1:
        return array[0][0]
    if len(array) == 2:
        return array[0][0]*array[1][1] - array[0][1]*array[1][0]
    det = 0
    for coluna in range(tamanho):
        submatriz = retirar_linha_coluna(array, 0, coluna)
        cofator = ((-1) ** coluna) * array[0][coluna] * determinante(submatriz)
        det += cofator  
    return det

def cofator(array, i, j):
    submatriz = retirar_linha_coluna(array, i, j)
    cofator_val = ((-1) ** (i + j)) * determinante(submatriz)
    return cofator_val

def matriz_transposta(array):
    transposta = []
    num_linhas = len(array)
    num_colunas = len(array[0])

    for j in range(num_colunas):
        nova_linha = []
        for i in range(num_linhas):
            nova_linha.append(array[i][j])
        transposta.append(nova_linha)
    return transposta


# Eliminação Gaussiana
def resolucao_matriz_triangular_superior(matrizA, matrizB):
    tamanho = len(matrizA)
    solucao = np.zeros(tamanho)
    
    for linha in range(tamanho - 1, -1, -1):
        soma = 0
        for coluna in range(linha + 1, tamanho):
            soma += matrizA[linha][coluna] * solucao[coluna] 
        
        solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha] 
        
    return solucao

def eliminacao_gaussiana(MatrizA, MatrizB):
    tamanho = len(MatrizA)
        
    for i in range(tamanho):
        
        for j in range(i + 1, tamanho):
            if MatrizA[i][i] != 0:
                mij = MatrizA[j][i] / MatrizA[i][i] 
                MatrizB[j] = MatrizB[j] - mij * MatrizB[i] 
                for k in range(i, tamanho):
                    MatrizA[j][k] = MatrizA[j][k] - mij * MatrizA[i][k] 
                
    resolucao = resolucao_matriz_triangular_superior(MatrizA, MatrizB)
    return resolucao


#### 🎯**Matrizes de teste**

In [4]:
matriz_chute = np.array([[1], [1], [1]])

matriz_a1 = np.array([[10, 1, 2], [1, 5, 1], [2, 3, 10]]) 
matriz_b1 = np.array([[-1], [1], [4]])

matriz_a2 = np.array([[3, 2, 4], [1, 1, 2], [4, 3, 2]])
matriz_b2 = np.array([[1], [2], [3]])

matriz_a3 = np.array([[1, 3, -1], [2, 6 , 1], [-1, 1, 4]])
matriz_b3 = np.array([[1], [0], [2]])

#### 🔴**Questão 1**

Faça um código em Python que resolva um sistema linear por meio do método de Gauss-Jacobi, verificando se uma matriz cumpre o critério de convergência de linhas.

*obs*: Para isso, utilize como critério de parada um número de iterações Iter ou um erro estipulado Err. 


In [5]:
def criterio_de_convergencia(matriz):
    criterio_de_linhas = True
    alfa_linhas = []
    for linha in matriz:
        soma_linhas = np.sum(linha)
        ultimo_elemento = abs(linha[-1])
        if ultimo_elemento != 0:
            alfak = soma_linhas / ultimo_elemento
            alfa_linhas.append(alfak)
        else:
            raise ValueError("Divisão por zero!")
               
    if max(alfa_linhas) <= 1:
            criterio_de_linhas = False

            
    return criterio_de_linhas    

In [6]:
def gauss_jacobi(MatrizA, MatrizB, Matriz_chute):
    """Implementação do método de Gauss-Jacobi com número máximo de iterações"""
    if criterio_de_convergencia(MatrizA):
        iteracoes_permitidas = 100
        tolerancia_permitida = 0.01
        tamanho = len(MatrizA)

        matriz_g = np.zeros((tamanho, 1))
        matriz_c = np.zeros((tamanho, tamanho))

        # Calcula matriz_g e matriz_c
        for i in range(tamanho):
            matriz_g[i] = MatrizB[i] / MatrizA[i, i]
            for j in range(tamanho):
                if j != i:
                    matriz_c[i, j] = -MatrizA[i, j] / MatrizA[i, i]
        
        for iteracao in range(iteracoes_permitidas):
            matriz_chute_linha = Matriz_chute.copy()
            Matriz_chute = matriz_c @ Matriz_chute + matriz_g

            distancia = np.max(np.abs(Matriz_chute - matriz_chute_linha))
            erro_relativo = distancia / (np.max(np.abs(Matriz_chute)))
            
            if erro_relativo < tolerancia_permitida:
                print(f"Convergência alcançada após {iteracao + 1} iterações.")
                return Matriz_chute
        
        print("Número máximo de iterações alcançado. A solução pode não ter convergido.")
        return Matriz_chute
    
    else:
        raise ValueError("A matriz A inserida pode não convergir, porque não é dominante na diagonal principal :(")

#### 🟡**Questão 2**

Considere os sistemas lineares abaixo. Utilize o programa desenvolvido no Exercício 1 para resolver apenas os sistemas que cumprem o critério das linhas.


In [7]:
gauss_jacobi(matriz_a1, matriz_b1, matriz_chute)

Convergência alcançada após 8 iterações.


array([[-0.19371456],
       [ 0.16129152],
       [ 0.39129792]])

In [8]:
gauss_jacobi(matriz_a2, matriz_b2, matriz_chute)

Número máximo de iterações alcançado. A solução pode não ter convergido.


array([[7.00107424e+44],
       [9.58661572e+44],
       [1.00441135e+45]])

In [9]:
gauss_jacobi(matriz_a3, matriz_b3, matriz_chute)

Número máximo de iterações alcançado. A solução pode não ter convergido.


array([[ 6.13700868e+08],
       [-1.92011015e+08],
       [ 1.66483160e+08]])

### 🟢 **Questão 3**

Apresente uma situação que satisfaça cada um dos casos abaixo:

1. O método direto (Eliminação Gaussiana ou LU) é mais adequado que o método iterativo (Gauss-Jacobi)



<p style="text-align: justify;">
Métodos diretos, tais como a eliminação gaussiana ou decomposição LU, são ideais para a resolução de <b>sistemas lineares menores </b>, visto que apresentam soluções precisas por meio de um grande número de iterações, as quais demandam grande custo computacional (complexidade O(n^3), ou seja, cresce cubicamente a partir do número de linhas). Ademais, esses métodos podem promover perda da estrutura da matriz - especialmente se essa for inicialmente esparsa.
<p>

*Exemplo de uso*

\begin{cases}
2x_1 + x_2 - x_3 = 2 \\
4x_1 + 3x_2 - 3x_3 = 3 \\
8x_1 - 7x_2 + x_3 = 1
\end{cases}

In [10]:
MatrizA = np.array([[2,1,1], [4,3,3], [8,7,9]])
MatrizB= np.array([[2], [3], [1]])

# Aqui utiluzei a eliminação gaussiana por se tratar de um sistema linear com apenas uma matriz B
eliminacao_gaussiana(MatrizA, MatrizB)

C:\Users\julia24002\AppData\Local\Temp\ipykernel_20796\1820129199.py:55: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  solucao[linha] = (matrizB[linha] - soma) / matrizA[linha][linha]


array([ 1.5,  1. , -2. ])

2. O método iterativo (Gauss-Jacobi) é mais adequado que o método direto (Eliminação Gaussiana ou LU) 

<p style="text-align: justify;">
O método de Gauss-Jacobi é especialmente vantajoso para a resolução de sistemas lineares onde a matriz é <b>esparsa</b>, ou seja, contém muitos elementos nulos. Em métodos diretos, mesmo com o auxílio do pivoteamento, os zeros podem causar instabilidade numérica na operação. Além disso, a matriz, originalmente esparsa, pode perder sua conformação, tornando-se mais densa ao longo do processo. Vale ressaltar ainda, que esse método pode ser eficaz em problemas grandes, nos quais a precisão não é um fator decisivo e o custo computacional é alto.
<p>

*Exemplo*

\begin{cases}
x_1 + 1/10x_3 = 1/3 \\
5x_2 + 1/5x_3= 1/10 \\
1/100x_1 + 2x_3 = 4/7


\end{cases}

In [11]:
MatrizA2 = np.array([
    [1, 0, 1/10],
    [0, 5, 1/5],
    [1/100, 0, 2]
])
MatrizB2= np.array([[1/3], [1/10], [4/7]])
gauss_jacobi(MatrizA2, MatrizB2, matriz_chute)

Convergência alcançada após 3 iterações.


array([[0.30487857],
       [0.0086181 ],
       [0.28418798]])

**Feedback**: Foi divertido :)

In [13]:
matriza = np.array([[1, 0.1, 0.001, 0.001], [1, 0.2, 0.04, 0.008], [1, 0.3, 0.09, 0.027], [1, 0.4, 0.16, 0.064]])
matrizb = np.array([5, 13, -4, -8])
gauss_jacobi(matriza, matrizb, [1,1,1,1])

Número máximo de iterações alcançado. A solução pode não ter convergido.


array([[-1.22391538e+22, -3.21729946e+21,  1.34716288e+22,
         3.03819966e+22],
       [-1.77219529e+23, -4.65855976e+22,  1.95065422e+23,
         4.39922824e+23],
       [-7.84938015e+23, -2.06336213e+23,  8.63980773e+23,
         1.94849942e+24],
       [-1.95104599e+24, -5.12870360e+23,  2.14751508e+24,
         4.84320024e+24]])